---
# Sync time first by restarting chronyd, useful for testing in snapshotted VM
- name: Ensure chrony is installed
  dnf:
    name: chrony
    state: present
  register: dnf_chrony_result
  retries: "{{ korora_task_retries }}"
  delay: "{{ korora_task_delay }}"
  until: dnf_chrony_result is succeeded
  become: true

- name: Restart chrony to sync time
  service:
    name: chronyd
    state: restarted
    enabled: yes
  changed_when: false
  become: true
